# Configure the management pi
- name: Ensure basic packages are installed
  apt:
    name:
    - python3-pip
    - git
    - curl
    - gnupg
    - rsyslog
    - iptables-persistent
    - minicom
    - yamllint
    - netcat-traditional
    state: present
    update_cache: true
  retries: 5
  delay: 10
  register: result
  until: result is success
  environment:
    DEBIAN_FRONTEND: noninteractive
- name: Disable Wi-Fi and Bluetooth
  copy:
    dest: /etc/modprobe.d/disable-wireless.conf
    content: |
      blacklist brcmfmac
      blacklist brcmutil
      blacklist bluetooth
      blacklist btusb
- name: Enable rsyslog service
  shell: sudo systemctl enable --now rsyslog
- name: Set iptables to allow outbound only
  shell: |
    # Clear existing IPTables config
    iptables -F
    iptables -X
    # Create new chain to handle logging dropped packets
    iptables -N LOGGING
    iptables -F LOGGING
    # Allow return traffic from outbound connections, loopback, and ICMP
    iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    iptables -A INPUT -i lo -j ACCEPT
    iptables -A INPUT -p icmp --icmp-type echo-reply -j ACCEPT
    # Send anything not headed to the loopback to the logging chain
    iptables -A INPUT ! -i lo -j LOGGING
    # Log all hits at a maximum of 5/min at the NOTICE log level, then drop them
    iptables -A LOGGING -m limit --limit 5\/minute -j LOG --log-prefix "IPTables-Dropped: " --log-level 5
    iptables -A LOGGING -j DROP
    # Set default policies
    iptables -P INPUT DROP
    iptables -P FORWARD DROP
    iptables -P OUTPUT ACCEPT
  become: true
- name: Save iptables rules for persistence
  shell: iptables-save > /etc/iptables/rules.v4
  become: true
