---
- name: Remove unused services
  hosts: local
  become: true
  gather_facts: false

  vars:
    removable_services:
    - name: avahi-daemon
      user: avahi
    - name: rpcbind
      user: _rpc
    - name: dnsmasq
      user: dnsmasq
    - name: cups
      user: lp
    - name: nfs-common
      user: statd
    - name: ssh
      user: sshd

  tasks:
  - name: Check for removable service unit files
    stat:
      path: "/lib/systemd/system/{{ item.name }}.service"
    loop: "{{ removable_services }}"
    register: service_status

  - name: Stop, disable, and mask unused services
    block:
    - name: Stop and disable unused services
      service:
        name: "{{ item.item.name }}"
        state: stopped
        enabled: false
      when: item.stat.exists
      loop: "{{ service_status.results }}"
      loop_control:
        label: "{{ item.item.user }}"
      ignore_errors: true
    - name: Mask unused services to prevent restart
      command: "systemctl mask {{ item.item.name }}"
      when: item.stat.exists
      loop: "{{ service_status.results }}"
      loop_control:
        label: "{{ item.item.user }}"
      ignore_errors: true
  - name: Delete user accounts for disabled services
    user:
      name: "{{ item.item.user }}"
      state: absent
      remove: yes
    when: item.stat.exists
    loop: "{{ service_status.results }}"
    loop_control:
      label: "{{ item.item.user }}"
  - name: Delete groups for disabled services
    group:
      name: "{{ item.item.user }}"
      state: absent
    when: item.stat.exists
    loop: "{{ service_status.results }}"
    loop_control:
      label: "{{ item.item.user }}"
