- name: test network_cli connection
  hosts: core_switch
  gather_facts: no

  tasks:
  - name: print connection type
    debug:
      var: ansible_connection
  - name: check connection
    cisco.ios.ios_facts:
      gather_subset: all
    register: ios_device_facts
  - name: display gathered facts
    debug:
      var: ios_device_facts.ansible_facts.ansible_net_hostname
